import type { RelationTermDef } from "./types";

/**
 * The plugin's bundled default: a STEM-flavored (math/formal-sciences)
 * vocabulary of 13 canonical Cypher labels behind 37 everyday terms. This is
 * only a starting point - it's written verbatim into the vault's relation
 * vocabulary file the first time it's needed, and from then on the file (not
 * this constant) is authoritative, so any vault can freely rename, remove, or
 * add terms for its own domain (medicine, law, project management, ...) in
 * whatever language it likes.
 *
 * `suggest: true` marks the lean subset offered to the local LLM for edge-type
 * suggestions - kept small on purpose so a small local model (e.g. a 1.5B
 * parameter one) can choose reliably; see relationVocabulary/llmSuggest.ts.
 */
export const DEFAULT_RELATION_VOCABULARY: RelationTermDef[] = [
  // Logic & Implication
  { key: "relImplies", label: "IMPLIES", term: "implies", category: "Logic & Implication", bidirectional: false, reversed: false, suggest: true },
  { key: "relSufficientCondition", label: "IMPLIES", term: "is sufficient condition for", category: "Logic & Implication", bidirectional: false, reversed: false },
  { key: "relProves", label: "IMPLIES", term: "proves", category: "Logic & Implication", bidirectional: false, reversed: false },
  { key: "relInduces", label: "IMPLIES", term: "induces", category: "Logic & Implication", bidirectional: false, reversed: false },
  { key: "relCharacterizes", label: "IMPLIES", term: "characterizes", category: "Logic & Implication", bidirectional: false, reversed: false },
  { key: "relFollowsFrom", label: "IMPLIES", term: "follows from", category: "Logic & Implication", bidirectional: false, reversed: true },
  { key: "relEquivalentTo", label: "EQUIVALENT_TO", term: "equivalent to", category: "Logic & Implication", bidirectional: true, reversed: false, suggest: true },
  { key: "relEquivDef", label: "EQUIVALENT_TO", term: "is equivalent definition to", category: "Logic & Implication", bidirectional: true, reversed: false },
  { key: "relCorresponds", label: "EQUIVALENT_TO", term: "corresponds to", category: "Logic & Implication", bidirectional: true, reversed: false },
  { key: "relContradicts", label: "CONFLICTS_WITH", term: "contradicts", category: "Logic & Implication", bidirectional: true, reversed: false },
  { key: "relIndependentOf", label: "INDEPENDENT_OF", term: "is independent of", category: "Logic & Implication", bidirectional: true, reversed: false },

  // Preconditions
  { key: "relBasedOn", label: "REQUIRES", term: "is based on", category: "Preconditions", bidirectional: false, reversed: false, suggest: true },
  { key: "relPresupposes", label: "REQUIRES", term: "presupposes", category: "Preconditions", bidirectional: false, reversed: false },
  { key: "relNecessaryCondition", label: "REQUIRES", term: "is necessary condition for", category: "Preconditions", bidirectional: false, reversed: true },

  // Generalization & Specialization
  { key: "relGeneralizes", label: "GENERALIZES", term: "generalizes", category: "Generalization & Specialization", bidirectional: false, reversed: false },
  { key: "relSpecialCase", label: "SPECIALIZES", term: "is special case of", category: "Generalization & Specialization", bidirectional: false, reversed: false, suggest: true },
  { key: "relExampleFor", label: "SPECIALIZES", term: "is example for", category: "Generalization & Specialization", bidirectional: false, reversed: false },
  { key: "relDegenerateCaseOf", label: "SPECIALIZES", term: "is degenerate case of", category: "Generalization & Specialization", bidirectional: false, reversed: false },
  { key: "relExtends", label: "EXTENDS", term: "extends", category: "Generalization & Specialization", bidirectional: false, reversed: false },
  { key: "relExtensionOf", label: "EXTENDS", term: "is extension of", category: "Generalization & Specialization", bidirectional: false, reversed: false },
  { key: "relAdjunctionOf", label: "EXTENDS", term: "arises by adjunction of", category: "Generalization & Specialization", bidirectional: false, reversed: false },

  // Proofs & Corollaries
  { key: "relReducesTo", label: "REDUCES_TO", term: "reduces to", category: "Proofs & Corollaries", bidirectional: false, reversed: false },
  { key: "relCorollaryOf", label: "REDUCES_TO", term: "is corollary of", category: "Proofs & Corollaries", bidirectional: false, reversed: false },
  { key: "relLemmaFor", label: "REDUCES_TO", term: "is lemma for", category: "Proofs & Corollaries", bidirectional: false, reversed: true },

  // Construction & Embedding
  { key: "relGeneratedBy", label: "CONSTRUCTS", term: "is generated by", category: "Construction & Embedding", bidirectional: false, reversed: false, suggest: true },
  { key: "relProductOf", label: "CONSTRUCTS", term: "is product of", category: "Construction & Embedding", bidirectional: false, reversed: false },
  { key: "relCoproductOf", label: "CONSTRUCTS", term: "is coproduct of", category: "Construction & Embedding", bidirectional: false, reversed: false },
  { key: "relQuotientOf", label: "CONSTRUCTS", term: "is quotient of", category: "Construction & Embedding", bidirectional: false, reversed: false },
  { key: "relClosedUnder", label: "CONSTRUCTS", term: "is closed under", category: "Construction & Embedding", bidirectional: false, reversed: false },
  { key: "relEmbeddedIn", label: "EMBEDS_IN", term: "is embedded in", category: "Construction & Embedding", bidirectional: false, reversed: false },
  { key: "relRetractsTo", label: "EMBEDS_IN", term: "retracts to", category: "Construction & Embedding", bidirectional: false, reversed: false },

  // Refutation & Counterexamples
  { key: "relRefutes", label: "REFUTES", term: "refutes", category: "Refutation & Counterexamples", bidirectional: false, reversed: false, suggest: true },
  { key: "relCounterexampleFor", label: "REFUTES", term: "is counterexample for", category: "Refutation & Counterexamples", bidirectional: false, reversed: false },

  // Structure & Analogy
  { key: "relAnalogousTo", label: "ANALOGOUS_TO", term: "is analogous to", category: "Structure & Analogy", bidirectional: true, reversed: false },
  { key: "relDualTo", label: "ANALOGOUS_TO", term: "is dual to", category: "Structure & Analogy", bidirectional: true, reversed: false },
  { key: "relOppositeOf", label: "ANALOGOUS_TO", term: "is opposite of", category: "Structure & Analogy", bidirectional: true, reversed: false },
  { key: "relIsomorphicTo", label: "ANALOGOUS_TO", term: "is isomorphic to", category: "Structure & Analogy", bidirectional: true, reversed: false },
];
